#ifndef MELEE_NATIVE_GX_METAL_SHADER_H
#define MELEE_NATIVE_GX_METAL_SHADER_H

/* Metal reads the native draw structures from gx_metal.h. Keep their scalar
 * array layout in sync. Compile this source with fast math disabled. */
static const char native_gx_metal_shader[] =
    "#include <metal_stdlib>\n"
    "using namespace metal;\n"
    "\n"
    "// Scalar arrays keep the buffer layout identical to gx_metal.h.\n"
    "struct NativeGXMetalVertex {\n"
    "    float position[4];\n"
    "    float color[2][4];\n"
    "    float texcoord[8][4];\n"
    "};\n"
    "struct NativeGXMetalCombiner {\n"
    "    uint input[4];\n"
    "    uint op, bias, scale, clamp, output;\n"
    "};\n"
    "struct NativeGXMetalStage {\n"
    "    NativeGXMetalCombiner color, alpha;\n"
    "    uint map, coord, raster, raster_swap, texture_swap, kcolor, kalpha;\n"
    "};\n"
    "struct NativeGXMetalState {\n"
    "    NativeGXMetalStage stage[16];\n"
    "    int registers[4][4];\n"
    "    uint konst[4][4];\n"
    "    uint swap[4][4];\n"
    "    uint stage_count;\n"
    "    uint z_compare, z_func, z_update, z_before_texture;\n"
    "    uint alpha_func[2], alpha_ref[2], alpha_op;\n"
    "    uint blend_mode, blend_src, blend_dst, logic_op;\n"
    "    uint color_update, alpha_update, dst_alpha_enabled, dst_alpha;\n"
    "    uint cull_mode;\n"
    "    uint scissor[4];\n"
    "    uint fog_type, fog_ortho, fog_range_enabled, fog_center;\n"
    "    float fog_start, fog_end, fog_near, fog_far;\n"
    "    float viewport_near, viewport_far;\n"
    "    float fog_color[4];\n"
    "    float fog_range[10];\n"
    "};\n"
    "\n"
    "struct NativeGXMetalVarying {\n"
    "    float4 position [[position]];\n"
    "    float4 color0 [[user(color0), center_no_perspective]];\n"
    "    float4 color1 [[user(color1), center_no_perspective]];\n"
    "    float3 tex0 [[user(tex0)]];\n"
    "    float3 tex1 [[user(tex1)]];\n"
    "    float3 tex2 [[user(tex2)]];\n"
    "    float3 tex3 [[user(tex3)]];\n"
    "    float3 tex4 [[user(tex4)]];\n"
    "    float3 tex5 [[user(tex5)]];\n"
    "    float3 tex6 [[user(tex6)]];\n"
    "    float3 tex7 [[user(tex7)]];\n"
    "};\n"
    "\n"
    "struct NativeGXMetalFragment {\n"
    "    float4 color [[color(0), index(0)]];\n"
    "    float4 blend [[color(0), index(1)]];\n"
    "};\n"
    "\n"
    "vertex NativeGXMetalVarying\n"
    "native_gx_vertex(const device NativeGXMetalVertex* vertices "
    "[[buffer(0)]],\n"
    "                 uint index [[vertex_id]])\n"
    "{\n"
    "    const device NativeGXMetalVertex& source = vertices[index];\n"
    "    NativeGXMetalVarying out;\n"
    "    out.position = float4(source.position[0], source.position[1],\n"
    "                          source.position[2], source.position[3]);\n"
    "    out.color0 = float4(source.color[0][0], source.color[0][1],\n"
    "                        source.color[0][2], source.color[0][3]);\n"
    "    out.color1 = float4(source.color[1][0], source.color[1][1],\n"
    "                        source.color[1][2], source.color[1][3]);\n"
    "    out.tex0 = float3(source.texcoord[0][0], source.texcoord[0][1],\n"
    "                      source.texcoord[0][2]);\n"
    "    out.tex1 = float3(source.texcoord[1][0], source.texcoord[1][1],\n"
    "                      source.texcoord[1][2]);\n"
    "    out.tex2 = float3(source.texcoord[2][0], source.texcoord[2][1],\n"
    "                      source.texcoord[2][2]);\n"
    "    out.tex3 = float3(source.texcoord[3][0], source.texcoord[3][1],\n"
    "                      source.texcoord[3][2]);\n"
    "    out.tex4 = float3(source.texcoord[4][0], source.texcoord[4][1],\n"
    "                      source.texcoord[4][2]);\n"
    "    out.tex5 = float3(source.texcoord[5][0], source.texcoord[5][1],\n"
    "                      source.texcoord[5][2]);\n"
    "    out.tex6 = float3(source.texcoord[6][0], source.texcoord[6][1],\n"
    "                      source.texcoord[6][2]);\n"
    "    out.tex7 = float3(source.texcoord[7][0], source.texcoord[7][1],\n"
    "                      source.texcoord[7][2]);\n"
    "    return out;\n"
    "}\n"
    "\n"
    "int native_gx_konst(const constant NativeGXMetalState& state, uint "
    "selector,\n"
    "                    uint channel, bool alpha)\n"
    "{\n"
    "    const int fractions[8] = { 255, 223, 191, 159, 128, 96, 64, 32 };\n"
    "    selector &= 31;\n"
    "    if (selector < 8) {\n"
    "        return fractions[selector];\n"
    "    }\n"
    "    if (!alpha && selector >= 12 && selector < 16) {\n"
    "        return state.konst[selector - 12][channel];\n"
    "    }\n"
    "    if (selector >= 16) {\n"
    "        return state.konst[selector & 3][(selector - 16) / 4];\n"
    "    }\n"
    "    return 0;\n"
    "}\n"
    "\n"
    "int native_gx_color_input(uint selector, uint channel,\n"
    "                          const thread int4* registers, int4 texture,\n"
    "                          int4 raster, int konst)\n"
    "{\n"
    "    if (selector <= 7) {\n"
    "        return registers[selector / 2][(selector & 1) ? 3 : channel];\n"
    "    }\n"
    "    switch (selector) {\n"
    "    case 8:\n"
    "        return texture[channel];\n"
    "    case 9:\n"
    "        return texture.a;\n"
    "    case 10:\n"
    "        return raster[channel];\n"
    "    case 11:\n"
    "        return raster.a;\n"
    "    case 12:\n"
    "        return 255;\n"
    "    case 13:\n"
    "        return 128;\n"
    "    case 14:\n"
    "        return konst;\n"
    "    default:\n"
    "        return 0;\n"
    "    }\n"
    "}\n"
    "\n"
    "int native_gx_alpha_input(uint selector, const thread int4* registers,\n"
    "                          int4 texture, int4 raster, int konst)\n"
    "{\n"
    "    if (selector <= 3) {\n"
    "        return registers[selector].a;\n"
    "    }\n"
    "    switch (selector) {\n"
    "    case 4:\n"
    "        return texture.a;\n"
    "    case 5:\n"
    "        return raster.a;\n"
    "    case 6:\n"
    "        return konst;\n"
    "    default:\n"
    "        return 0;\n"
    "    }\n"
    "}\n"
    "\n"
    "int native_gx_clamp(int value, uint enabled)\n"
    "{\n"
    "    return clamp(value, enabled ? 0 : -1024, enabled ? 255 : 1023);\n"
    "}\n"
    "\n"
    "// Keep the same integer rounding and signed register range as "
    "gx_tev.h.\n"
    "int native_gx_arithmetic(const constant NativeGXMetalCombiner& combiner, "
    "int a,\n"
    "                         int b, int c, int d)\n"
    "{\n"
    "    int factor = c + (c >> 7);\n"
    "    int interpolation = a * 256 + (b - a) * factor;\n"
    "    int scale = combiner.scale == 3 ? 1 : 1 << combiner.scale;\n"
    "    if (combiner.bias == 1) {\n"
    "        d += 128;\n"
    "    }\n"
    "    if (combiner.bias == 2) {\n"
    "        d -= 128;\n"
    "    }\n"
    "    interpolation *= scale;\n"
    "    if (combiner.scale != 3) {\n"
    "        interpolation += combiner.op == 1 ? 127 : 128;\n"
    "    }\n"
    "    int value = d * scale + (combiner.op == 1 ? -(interpolation >> 8)\n"
    "                                              : interpolation >> 8);\n"
    "    if (combiner.scale == 3) {\n"
    "        value >>= 1;\n"
    "    }\n"
    "    return native_gx_clamp(value, combiner.clamp);\n"
    "}\n"
    "\n"
    "bool native_gx_tev_compare(uint op, int4 a, int4 b, uint channel)\n"
    "{\n"
    "    uint mode = (op >> 1) & 3;\n"
    "    int left = a[channel], right = b[channel];\n"
    "    if (mode < 3) {\n"
    "        left = a.r;\n"
    "        right = b.r;\n"
    "        if (mode >= 1) {\n"
    "            left += a.g * 256;\n"
    "            right += b.g * 256;\n"
    "        }\n"
    "        if (mode == 2) {\n"
    "            left += a.b * 65536;\n"
    "            right += b.b * 65536;\n"
    "        }\n"
    "    }\n"
    "    return (op & 1) ? left == right : left > right;\n"
    "}\n"
    "\n"
    "int4 native_gx_tev(NativeGXMetalVarying in,\n"
    "                   const constant NativeGXMetalState& state,\n"
    "                   array<texture2d<float>, 8> textures,\n"
    "                   array<sampler, 8> samplers)\n"
    "{\n"
    "    int4 registers[4];\n"
    "    for (uint i = 0; i < 4; ++i) {\n"
    "        registers[i] = int4(state.registers[i][0], "
    "state.registers[i][1],\n"
    "                            state.registers[i][2], "
    "state.registers[i][3]);\n"
    "    }\n"
    "    int4 raster0 = int4(clamp(in.color0, 0.0f, 255.0f));\n"
    "    int4 raster1 = int4(clamp(in.color1, 0.0f, 255.0f));\n"
    "    int4 result = raster0;\n"
    "    float3 coords[8] = { in.tex0, in.tex1, in.tex2, in.tex3,\n"
    "                         in.tex4, in.tex5, in.tex6, in.tex7 };\n"
    "    for (uint index = 0; index < min(state.stage_count, 16u); ++index) "
    "{\n"
    "        const constant NativeGXMetalStage& stage = state.stage[index];\n"
    "        int4 sampled = int4(255), raster_color = int4(0);\n"
    "        uint map = stage.map & ~0x100u;\n"
    "        uint coord = stage.coord < 8 ? stage.coord : 0;\n"
    "        if (map < 8 && !(stage.map & 0x100u)) {\n"
    "            float3 stq = coords[coord];\n"
    "            float2 uv = stq.xy * (abs(stq.z) > 1.0e-20f ? 1.0f / stq.z : "
    "1.0f);\n"
    "            if (all(isfinite(uv))) {\n"
    "                sampled = int4(clamp(\n"
    "                    floor(textures[map].sample(samplers[map], uv) * "
    "255.0f +\n"
    "                          0.5f),\n"
    "                    0.0f, 255.0f));\n"
    "            }\n"
    "        }\n"
    "        switch (stage.raster) {\n"
    "        case 0:\n"
    "        case 2:\n"
    "        case 4:\n"
    "            raster_color = raster0;\n"
    "            break;\n"
    "        case 1:\n"
    "        case 3:\n"
    "        case 5:\n"
    "            raster_color = raster1;\n"
    "            break;\n"
    "        default:\n"
    "            break;\n"
    "        }\n"
    "        int4 texture, raster;\n"
    "        for (uint channel = 0; channel < 4; ++channel) {\n"
    "            texture[channel] =\n"
    "                sampled[state.swap[stage.texture_swap & 3][channel] & "
    "3];\n"
    "            raster[channel] =\n"
    "                raster_color[state.swap[stage.raster_swap & 3][channel] "
    "& 3];\n"
    "        }\n"
    "        // Both combiners read all inputs before either output register\n"
    "        // changes.\n"
    "        int4 inputs[4];\n"
    "        for (uint input = 0; input < 4; ++input) {\n"
    "            for (uint channel = 0; channel < 3; ++channel) {\n"
    "                inputs[input][channel] = native_gx_color_input(\n"
    "                    stage.color.input[input], channel, registers, "
    "texture,\n"
    "                    raster,\n"
    "                    native_gx_konst(state, stage.kcolor, channel, "
    "false));\n"
    "            }\n"
    "            inputs[input].a = native_gx_alpha_input(\n"
    "                stage.alpha.input[input], registers, texture, raster,\n"
    "                native_gx_konst(state, stage.kalpha, 3, true));\n"
    "            if (input < 3) {\n"
    "                inputs[input] &= 255;\n"
    "            }\n"
    "        }\n"
    "        for (uint channel = 0; channel < 4; ++channel) {\n"
    "            const constant NativeGXMetalCombiner& combiner =\n"
    "                channel == 3 ? stage.alpha : stage.color;\n"
    "            if (combiner.op >= 8) {\n"
    "                bool test = native_gx_tev_compare(combiner.op, "
    "inputs[0],\n"
    "                                                  inputs[1], channel);\n"
    "                result[channel] = native_gx_clamp(\n"
    "                    inputs[3][channel] + (test ? inputs[2][channel] : "
    "0),\n"
    "                    combiner.clamp);\n"
    "            } else {\n"
    "                result[channel] = native_gx_arithmetic(\n"
    "                    combiner, inputs[0][channel], inputs[1][channel],\n"
    "                    inputs[2][channel], inputs[3][channel]);\n"
    "            }\n"
    "            registers[combiner.output & 3][channel] = result[channel];\n"
    "        }\n"
    "    }\n"
    "    return result & 255;\n"
    "}\n"
    "\n"
    "bool native_gx_compare(uint source, uint dest, uint func)\n"
    "{\n"
    "    switch (func) {\n"
    "    case 0:\n"
    "        return false;\n"
    "    case 1:\n"
    "        return source < dest;\n"
    "    case 2:\n"
    "        return source == dest;\n"
    "    case 3:\n"
    "        return source <= dest;\n"
    "    case 4:\n"
    "        return source > dest;\n"
    "    case 5:\n"
    "        return source != dest;\n"
    "    case 6:\n"
    "        return source >= dest;\n"
    "    case 7:\n"
    "        return true;\n"
    "    default:\n"
    "        return false;\n"
    "    }\n"
    "}\n"
    "\n"
    "bool native_gx_alpha_pass(uint alpha, const constant NativeGXMetalState& "
    "state)\n"
    "{\n"
    "    bool a = native_gx_compare(alpha, state.alpha_ref[0], "
    "state.alpha_func[0]);\n"
    "    bool b = native_gx_compare(alpha, state.alpha_ref[1], "
    "state.alpha_func[1]);\n"
    "    switch (state.alpha_op) {\n"
    "    case 0:\n"
    "        return a && b;\n"
    "    case 1:\n"
    "        return a || b;\n"
    "    case 2:\n"
    "        return a != b;\n"
    "    case 3:\n"
    "        return a == b;\n"
    "    default:\n"
    "        return false;\n"
    "    }\n"
    "}\n"
    "\n"
    "float native_gx_fog_range(int x, const constant NativeGXMetalState& "
    "state)\n"
    "{\n"
    "    if (!state.fog_range_enabled) {\n"
    "        return 1.0f;\n"
    "    }\n"
    "    float distance = abs(float(x) - (int(state.fog_center) - 342));\n"
    "    float index = distance / 32.0f;\n"
    "    if (index >= 10.0f) {\n"
    "        return state.fog_range[9] / 256.0f;\n"
    "    }\n"
    "    uint upper = uint(index);\n"
    "    float lower_value = upper == 0 ? 256.0f : state.fog_range[upper - "
    "1];\n"
    "    return (lower_value +\n"
    "            (state.fog_range[upper] - lower_value) * (index - upper)) /\n"
    "           256.0f;\n"
    "}\n"
    "\n"
    "int4 native_gx_fog(int4 color, float depth, int x,\n"
    "                   const constant NativeGXMetalState& state)\n"
    "{\n"
    "    uint type = state.fog_type & 7;\n"
    "    float viewport_range = state.viewport_far - state.viewport_near;\n"
    "    if (type == 0 || !isfinite(depth) || !isfinite(viewport_range) ||\n"
    "        viewport_range == 0.0f)\n"
    "    {\n"
    "        return color;\n"
    "    }\n"
    "    float normalized = (depth - state.viewport_near) / viewport_range;\n"
    "    if (!isfinite(normalized)) {\n"
    "        return color;\n"
    "    }\n"
    "    normalized = clamp(normalized, 0.0f, 1.0f);\n"
    "    float distance, start;\n"
    "    if (state.fog_ortho || (state.fog_type & 8)) {\n"
    "        distance = normalized * (state.fog_far - state.fog_near);\n"
    "        start = state.fog_start - state.fog_near;\n"
    "    } else {\n"
    "        float denominator =\n"
    "            state.fog_far - normalized * (state.fog_far - "
    "state.fog_near);\n"
    "        if (denominator == 0.0f) {\n"
    "            return color;\n"
    "        }\n"
    "        distance = state.fog_near * state.fog_far / denominator;\n"
    "        start = state.fog_start;\n"
    "    }\n"
    "    float amount = (distance * native_gx_fog_range(x, state) - start) /\n"
    "                   (state.fog_end - state.fog_start);\n"
    "    amount = clamp(amount, 0.0f, 1.0f);\n"
    "    switch (type) {\n"
    "    case 2:\n"
    "        break;\n"
    "    case 4:\n"
    "        amount = 1.0f - exp2(-8.0f * amount);\n"
    "        break;\n"
    "    case 5:\n"
    "        amount = 1.0f - exp2(-8.0f * amount * amount);\n"
    "        break;\n"
    "    case 6:\n"
    "        amount = exp2(-8.0f * (1.0f - amount));\n"
    "        break;\n"
    "    case 7:\n"
    "        amount = 1.0f - amount;\n"
    "        amount = exp2(-8.0f * amount * amount);\n"
    "        break;\n"
    "    default:\n"
    "        return color;\n"
    "    }\n"
    "    uint factor = uint(floor(amount * 256.0f + 0.5f));\n"
    "    int3 fog_color =\n"
    "        int3(state.fog_color[0], state.fog_color[1], "
    "state.fog_color[2]);\n"
    "    color.rgb = (color.rgb * int(256 - factor) + fog_color * "
    "int(factor)) >> 8;\n"
    "    return color;\n"
    "}\n"
    "\n"
    "NativeGXMetalFragment native_gx_fragment_value(\n"
    "    NativeGXMetalVarying in, const constant NativeGXMetalState& state,\n"
    "    array<texture2d<float>, 8> textures, array<sampler, 8> samplers)\n"
    "{\n"
    "    int4 color = native_gx_tev(in, state, textures, samplers);\n"
    "    if (!native_gx_alpha_pass(color.a, state)) {\n"
    "        discard_fragment();\n"
    "    }\n"
    "    color = native_gx_fog(color, in.position.z, int(in.position.x), "
    "state);\n"
    "    NativeGXMetalFragment out;\n"
    "    out.blend = float4(color) / 255.0f;\n"
    "    out.color = out.blend;\n"
    "    if (state.dst_alpha_enabled) {\n"
    "        out.color.a = float(state.dst_alpha & 255) / 255.0f;\n"
    "    }\n"
    "    return out;\n"
    "}\n"
    "\n"
    "fragment NativeGXMetalFragment\n"
    "native_gx_fragment(NativeGXMetalVarying in [[stage_in]],\n"
    "                   const constant NativeGXMetalState& state "
    "[[buffer(1)]],\n"
    "                   array<texture2d<float>, 8> textures [[texture(0)]],\n"
    "                   array<sampler, 8> samplers [[sampler(0)]])\n"
    "{\n"
    "    return native_gx_fragment_value(in, state, textures, samplers);\n"
    "}\n"
    "\n"
    "[[early_fragment_tests]]\n"
    "fragment NativeGXMetalFragment native_gx_fragment_early(\n"
    "    NativeGXMetalVarying in [[stage_in]],\n"
    "    const constant NativeGXMetalState& state [[buffer(1)]],\n"
    "    array<texture2d<float>, 8> textures [[texture(0)]],\n"
    "    array<sampler, 8> samplers [[sampler(0)]])\n"
    "{\n"
    "    return native_gx_fragment_value(in, state, textures, samplers);\n"
    "}\n";

#endif
